<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_bolsa_users_cambio_contrasenha  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeShowAdd"]=true;

		$this->events["BeforeShowEdit"]=true;

		$this->events["CustomEdit"]=true;


		$this->events["AfterEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowAdd(&$xt, &$templatefile, $pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.
$pageObject->hideItem("integrated_edit_field", $recordId); //Oculta el campo nro_documento
$pageObject->hideItem("integrated_edit_field3", $recordId); //Oculta el campo groupid
$pageObject->hideItem("integrated_edit_field4", $recordId);  //Oculta el campo active
$pageObject->hideItem("integrated_edit_field5", $recordId); //Oculta el campo reset_token
$pageObject->hideItem("integrated_edit_field6", $recordId); //Oculta el campo reset_date
$pageObject->hideItem("integrated_edit_field7", $recordId); //Oculta el campo fecha_alta
$pageObject->hideItem("integrated_edit_field8", $recordId); //Oculta el campo llave
$pageObject->hideItem("integrated_edit_field9", $recordId); //Oculta el campo estado_llave
$pageObject->hideItem("integrated_edit_field15", $recordId); //Oculta el campo senadis
$pageObject->hideItem("integrated_edit_field16", $recordId); //Oculta el campo trabajo_antes
$pageObject->hideItem("integrated_edit_field10", $recordId); //Oculta el campo personaid
$pageObject->hideItem("integrated_edit_field11", $recordId); //Oculta el campo fullname
$pageObject->hideItem("integrated_edit_field12", $recordId); //Oculta el campo username
$pageObject->hideItem("integrated_edit_field13", $recordId); //Oculta el campo hash_generado
$pageObject->hideItem("integrated_edit_field14", $recordId); //Oculta el campo adjunto_foto_perfil

$pageObject->hideItem("add_back_list", $recordId); //Oculta el boton "Volver a la lista"
;		
} // function BeforeShowAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowEdit(&$xt, &$templatefile, $values, $pageObject)
{

		
//Al mostrar el formulario ocultar los campos que no son necesarios que sean visibles para actualizacion de contraseña.
//$pageObject->hideItem("integrated_edit_field18", $recordId); //Oculta el campo id
$pageObject->hideItem("campo_id"); //Oculta el campo id
$pageObject->hideItem("integrated_edit_field", $recordId); //Oculta el campo nro_documento
$pageObject->hideItem("integrated_edit_field3", $recordId); //Oculta el campo groupid
$pageObject->hideItem("integrated_edit_field4", $recordId); //Oculta el campo active
$pageObject->hideItem("integrated_edit_field5", $recordId);  //Oculta el campo reset_token
$pageObject->hideItem("integrated_edit_field6", $recordId); //Oculta el campo reset_date
$pageObject->hideItem("integrated_edit_field7", $recordId); //Oculta el campo fecha_alta
$pageObject->hideItem("integrated_edit_field8", $recordId); //Oculta el campo llave
$pageObject->hideItem("integrated_edit_field9", $recordId); //Oculta el campo estado_llave
$pageObject->hideItem("integrated_edit_field15", $recordId); //Oculta el campo senadis
$pageObject->hideItem("integrated_edit_field16", $recordId); //Oculta el campo trabajo_antes
$pageObject->hideItem("integrated_edit_field10", $recordId); //Oculta el campo personaid
$pageObject->hideItem("integrated_edit_field11", $recordId); //Oculta el campo fullname
$pageObject->hideItem("integrated_edit_field12", $recordId); //Oculta el campo username
$pageObject->hideItem("integrated_edit_field13", $recordId); //Oculta el campo hash_generado
$pageObject->hideItem("integrated_edit_field14", $recordId); //Oculta el campo adjunto_foto_perfil
$pageObject->hideItem("integrated_edit_field2", $recordId); //Oculta el campo email
$pageObject->hideItem("edit_save", $recordId); //Oculta el boton predefinido para guardar

$pageObject->hideItem("campo_llave_id");	//Oculta el campo llave_id(utilizado para validacion de cambio de contrasenha).


if ($_SESSION["bandera_cambio_contrasenha"] == 1) {
	//mostrar campos
	//$pageObject->showItem("integrated_edit_field2"); //mostrar campo email
	$pageObject->showItem("integrated_edit_field19"); //mostrar campo phone
	//ocultar boton
	$pageObject->hideItem("custom_button1"); //ocultar el boton "Volver"
} else {
	//ocultar campos, ocultar boton desconectarse
	//$pageObject->hideItem("integrated_edit_field2"); //ocultar campo email
	$pageObject->hideItem("integrated_edit_field19"); //ocultar campo phone
	$pageObject->hideItem("logout_link1"); //Ocultar boton "desconectarse"
	//mostrar boton
	$pageObject->showItem("custom_button1"); //mostrar el boton "Volver"
}


/*La variable de Sesion "cantidad_omision_cambio_password" existe solo si se realiza la verificacion al loquearse
que el usuario aun no realizo su cambio de contraseña.*/
if ($_SESSION["cantidad_omision_cambio_password"] == 0) {
	//ocultar boton de omision de cambio de contrasenha
	$pageObject->hideItem("custom_button2"); //ocultar el boton "Omision"
}
;		
} // function BeforeShowEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom record update
function CustomEdit(&$values, $where, &$oldvalues, &$keys, &$error, $inline, $pageObject)
{

		
	return false;
;		
} // function CustomEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		unset($_SESSION['bandera_cambio_contrasenha']);

//**********  Redirect to vacancia_list page  ************
header("Location: vacancia_list.php");
exit();


;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
