<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_cvc_movilidad  extends eventsBase
{
	function __construct()
	{
	// fill list of events

		$this->events["CustomEdit"]=true;

		$this->events["BeforeProcessEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom record update
function CustomEdit(&$values, $where, &$oldvalues, &$keys, &$error, $inline, $pageObject)
{

		function debug_to_console($data, $context = 'Debug in Console') {

    // Buffering to solve problems frameworks, like header() in this and not a solid return.
    ob_start();

    $output  = 'console.info(\'' . $context . ':\');';
    $output .= 'console.log(' . json_encode($data) . ');';
    $output  = sprintf('<script>%s</script>', $output);

    echo $output;
}

	  
										$sql2 = DB::PrepareSQL("update bolsa_empleo.cvc_movilidad set movilidad_propia = ':1',
										registro_conducir = ':2', tipo_movilidad = ':3', ids_tipo_registro_conducir = ':4' 
										where fk_persona_id = ':5'",$values["movilidad_propia"],$values["registro_conducir"],$values["tipo_movilidad"],
										$values["ids_tipo_registro_conducir"],$keys["fk_persona_id"]);

										debug_to_console($sql2);

										DB::Exec($sql2);


return false;
;		
} // function CustomEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
				// Edit page: Before process
function BeforeProcessEdit($pageObject)
{

		function debug_to_console($data, $context = 'Debug in Console') {

    // Buffering to solve problems frameworks, like header() in this and not a solid return.
    ob_start();

    $output  = 'console.info(\'' . $context . ':\');';
    $output .= 'console.log(' . json_encode($data) . ');';
    $output  = sprintf('<script>%s</script>', $output);

    echo $output;
}




$strSQLExistsic = "SELECT * FROM bolsa_empleo.cvc_movilidad WHERE fk_persona_id='".pg_escape_string($_SESSION["persona_id"])."'";
										$rsExistsic = db_query($strSQLExistsic,$conn);
										$dataic=db_fetch_array($rsExistsic);

										if(!$dataic)
										{


										$sql2 = DB::PrepareSQL("INSERT INTO bolsa_empleo.cvc_movilidad(fk_persona_id) values (':1'))",$_SESSION["persona_id"]);

										debug_to_console($sql2);
										DB::Exec($sql2);



										}
;		
} // function BeforeProcessEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
