<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_cvc_programas  extends eventsBase
{
	function __construct()
	{
	// fill list of events

		$this->events["BeforeShowList"]=true;



		$this->events["AfterAdd"]=true;



	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

		$xt->assign("message", "Sin Datos. Añadir Información");

$pageObject->hideItem("simple_grid_field");
;		
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		$textoresultados = array();
$falta_datos = 0;



$rs = DB::Query("
    SELECT
        (SELECT foto FROM eportal.persons WHERE id = '".pg_escape_string($_SESSION["persona_id"])."') AS existe_foto,
        (SELECT resumen FROM eportal.persons WHERE id = '".pg_escape_string($_SESSION["persona_id"])."') AS existe_resumen,
        (SELECT COUNT(*) FROM eportal.persons_phones WHERE person_id = '".pg_escape_string($_SESSION["persona_id"])."') AS count_phones,
        (SELECT city_id FROM eportal.persons WHERE id = '".pg_escape_string($_SESSION["persona_id"])."') AS existe_city,
        (SELECT domicilio  FROM eportal.persons WHERE id = '".pg_escape_string($_SESSION["persona_id"])."') AS existe_domicilio,
        (SELECT canthijos FROM eportal.persons WHERE id = '".pg_escape_string($_SESSION["persona_id"])."') AS existe_canthijos,
        (SELECT COUNT(*) FROM bolsa_empleo.vista_estudios_realizados_union_mec WHERE nro_documento = '".pg_escape_string($_SESSION["cedula"])."') AS count_educacion
" );


    while ($datafinal = $rs->fetchAssoc()) {


			 $existe_foto = $datafinal['existe_foto'];
       $existe_resumen = $datafinal['existe_resumen'];
       $count_phones = $datafinal['count_phones'];
       $existe_city = $datafinal['existe_city'];
       $existe_domicilio = $datafinal['existe_domicilio'];
       $existe_canthijos = $datafinal['existe_canthijos'];
       $count_educacion = $datafinal['count_educacion'];


        if (is_null($existe_foto)) {
           // $textoresultados[] = '<br><i class="bi bi-dot"></i> '."Foto de Perfil en Informacion Personal.";
						// $falta_datos = 1;
				
        }

        if (is_null($existe_resumen)) {
            $textoresultados[] = '<br><i class="bi bi-dot"></i> '."Resumen Personal <a href='persons_edit.php'>Ir a información personal</a>";
						 $falta_datos = 1;
        }

				 if ($count_phones < 1) {
            $textoresultados[] = '<br><i class="bi bi-dot"></i> '."1 Numero de Contacto <a href='persons_phones_list.php'>Ir a teléfonos</a>";
						 $falta_datos = 1;
        }

				 if (is_null($existe_city)) {
            $textoresultados[] = '<br><i class="bi bi-dot"></i> '."Ciudad <a href='persons_edit.php'>Ir a información personal</a>";
						 $falta_datos = 1;
        }

				 if (is_null($existe_domicilio)) {
            $textoresultados[] = '<br><i class="bi bi-dot"></i> '."Dirección. <a href='persons_edit.php'>Ir a información personal</a>";
						 $falta_datos = 1;
        }

         if (is_null($existe_canthijos)) {
            $textoresultados[] = '<br><i class="bi bi-dot"></i> '."Cantidad Hijos <a href='persons_edit.php'>Ir a información personal</a>";
						 $falta_datos = 1;
        }

				
         if ($count_educacion < 1 ) {
            $textoresultados[] = '<br><i class="bi bi-dot"></i> '."1 Entidad Educativa <a href='vista_estudios_realizados_union_mec_list.php'>Ir a Estudios Realizados</a>";
						 $falta_datos = 1;
        }

    }



if ($falta_datos == '0' ){

$pageObject->setMessageType(MESSAGE_INFO);
$Mensaje='<h4><span style="color: #000000; ">Información Registrada Correctamente</span></h4><p style="color: #000000; "> ¡Ahora puedes postularte!</p>
<div>

			
	

		<a class="btn btn-sm btn-success" href="vacancia_list.php" id="viewPageButton1">Ir a las Ofertas Laborales</a>

</div>';
$pageObject->setMessage($Mensaje);



}
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
