<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_cvc_movilidad  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterEdit"]=true;

		$this->events["BeforeAdd"]=true;

		$this->events["AfterDelete"]=true;

		$this->events["AfterAdd"]=true;

		$this->events["BeforeShowList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

			//borrar y volver a cargar movilidad_detalle_cvc
	$sqlDelete = DB::PrepareSQL("DELETE FROM bolsa_empleo.movilidad_detalle_cvc WHERE id_persona_pk = ':1'", $values["fk_persona_id"]);
	DB::Exec($sqlDelete);
	//insertar movilidad_detalle_cvc
	$tiposMovilidades = explode(",", $values["tipo_movilidad"]);
	foreach ($tiposMovilidades as $value) {
    $sqlInsert = DB::PrepareSQL("INSERT INTO bolsa_empleo.movilidad_detalle_cvc(id_persona_pk, id_tipo_movilidad_cvc) VALUES (':1',':2')", $values["fk_persona_id"], $value);
    DB::Exec($sqlInsert);
	}

	//borrar y volver a cargar registro_conducir_detalle_cvc
	$sqlDelete = DB::PrepareSQL("DELETE FROM bolsa_empleo.registro_conducir_detalle_cvc WHERE id_persona_pk = ':1'", $values["fk_persona_id"]);
	DB::Exec($sqlDelete);
	//insertar registro_conducir_detalle_cvc
	$tiposRegistroConducir = explode(",", $values["ids_tipo_registro_conducir"]);
	foreach ($tiposRegistroConducir as $value) {
    $sqlInsert = DB::PrepareSQL("INSERT INTO bolsa_empleo.registro_conducir_detalle_cvc(id_persona_pk, id_tipo_registro_conducir_cvc) VALUES (':1',':2')", $values["fk_persona_id"], $value);
    DB::Exec($sqlInsert);
	}
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$sqlValues, &$message, $inline, $pageObject)
{

		/*	
//insertar movilidad_detalle_cvc
	$tiposMovilidades = explode(",", $values["tipo_movilidad"]);
	foreach ($tiposMovilidades as $value) {
    //$sqlInsert = DB::PrepareSQL("INSERT INTO bolsa_empleo.movilidad_detalle_cvc(id_persona_pk, id_tipo_movilidad_cvc) VALUES (':1',':2')", $values["fk_persona_id"], $value);
		$sqlInsert = DB::PrepareSQL("INSERT INTO bolsa_empleo.movilidad_detalle_cvc(id_persona_pk, id_tipo_movilidad_cvc, fk_cvc_id_movilidad) 
																		VALUES (':1',':2', ':3')", 
																							$values["fk_persona_id"], 
																							$value, 
																							$values["cvc_id_movilidad"]);
    DB::Exec($sqlInsert);
	}
	
	//insertar registro_conducir_detalle_cvc
	$tiposRegistroConducir = explode(",", $values["ids_tipo_registro_conducir"]);
	foreach ($tiposRegistroConducir as $value) {
    //$sqlInsert = DB::PrepareSQL("INSERT INTO bolsa_empleo.registro_conducir_detalle_cvc(id_persona_pk, id_tipo_registro_conducir_cvc) VALUES (':1',':2')", $values["fk_persona_id"], $value);
		$sqlInsert = DB::PrepareSQL("INSERT INTO bolsa_empleo.registro_conducir_detalle_cvc(id_persona_pk, id_tipo_registro_conducir_cvc) 
																			VALUES (':1',':2', ':3')", 
																								$values["fk_persona_id"], 
																								$value,
																								$values["cvc_id_movilidad"]
																		);
    DB::Exec($sqlInsert);
	}
*/
	return true;

;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record deleted
function AfterDelete($where, &$deleted_values, &$message, $pageObject)
{

			//Eliminar movilidad_detalle_cvc
	$sqlDelete = DB::PrepareSQL("DELETE 
																		FROM bolsa_empleo.movilidad_detalle_cvc 
																		WHERE id_persona_pk = ':1'", 
																		$deleted_values["fk_persona_id"]);
	DB::Exec($sqlDelete);

	//Eliminar registro_conducir_detalle_cvc
	$sqlDelete = DB::PrepareSQL("DELETE 
																		FROM bolsa_empleo.registro_conducir_detalle_cvc 
																		WHERE id_persona_pk = ':1'", 
																		$deleted_values["fk_persona_id"]);
	DB::Exec($sqlDelete);
;		
} // function AfterDelete

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

			//insertar movilidad_detalle_cvc
	$tiposMovilidades = explode(",", $values["tipo_movilidad"]);
	foreach ($tiposMovilidades as $value) {
    //$sqlInsert = DB::PrepareSQL("INSERT INTO bolsa_empleo.movilidad_detalle_cvc(id_persona_pk, id_tipo_movilidad_cvc) VALUES (':1',':2')", $values["fk_persona_id"], $value);
		$sqlInsert = DB::PrepareSQL("INSERT INTO bolsa_empleo.movilidad_detalle_cvc(id_persona_pk, id_tipo_movilidad_cvc, fk_cvc_id_movilidad) 
																		VALUES (':1',':2', ':3')", 
																							$_SESSION["persona_id"], 
																							$value, 
																							$keys["cvc_id_movilidad"]);
    DB::Exec($sqlInsert);
	}
	
	//insertar registro_conducir_detalle_cvc
	$tiposRegistroConducir = explode(",", $values["ids_tipo_registro_conducir"]);
	foreach ($tiposRegistroConducir as $value) {
    //$sqlInsert = DB::PrepareSQL("INSERT INTO bolsa_empleo.registro_conducir_detalle_cvc(id_persona_pk, id_tipo_registro_conducir_cvc) VALUES (':1',':2')", $values["fk_persona_id"], $value);
		$sqlInsert = DB::PrepareSQL("INSERT INTO bolsa_empleo.registro_conducir_detalle_cvc(id_persona_pk, id_tipo_registro_conducir_cvc, fk_cvc_id_movilidad) 
																			VALUES (':1',':2', ':3')", 
																								$_SESSION["persona_id"], 
																								$value,
																								$keys["cvc_id_movilidad"]
																		);
    DB::Exec($sqlInsert);
	}

;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

		$pageObject->hideItem("grid_field"); //oculta vacancia cvc_id_movilidad
$pageObject->hideItem("grid_field1"); //oculta fk_persona_id
;		
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
