<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_detalle_vacancia  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeMoveNextList"]=true;

		$this->events["BeforeShowList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		$pageObject->hideItem("custom_cancelar_postu"); //custom_button1
$pageObject->hideItem("custom_postularse"); //custom_button


//vacancia cerrada
if ($data['id_estado'] == 5) {
	$pageObject->hideItem("text23", $recordId);
	$pageObject->hideItem("grid_field16", $recordId); 
}


//por econom[ia, oculto hasta poder terminar la logina
/*
if (Security::isLoggedIn()) {
$strSQLExistsl = "SELECT
	*
FROM
	bolsa_empleo.postulacion
WHERE
id_vacancia='".pg_escape_string($data["id_vacancias"])."' and fk_personaid='".pg_escape_string($_SESSION["persona_id"])."' ";
$rsExistsl = db_query($strSQLExistsl,$conn);
$datal=db_fetch_array($rsExistsl);
	if($datal)
			{

  //ya se postulo!

$pageObject->hideItem("custom_postularse");
$pageObject->showItem("custom_cancelar_postu");


			}else{

       $pageObject->showItem("custom_postularse");
      }
}

*/
;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

		//$pageObject->hideItem("grid_field9");
;		
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
