<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_personas_pasos  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeEdit"]=true;

		$this->events["CustomEdit"]=true;

		$this->events["ProcessValuesEdit"]=true;



		$this->events["AfterEdit"]=true;

		$this->events["BeforeShowEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record updated
function BeforeEdit(&$values, &$sqlValues, $where, &$oldvalues, &$keys, &$message, $inline, $pageObject)
{

		$cantidadDeElementos = 0;
	$existeEntregaEnArray = 0;

	//verificar que sea valido seleccion de discapacidades
	$id_multados_multi = explode(",", $values['multiselect_discapacidades']);
	foreach ($id_multados_multi as $valueToInsert) {
		if ($valueToInsert == '1') {
			$existeEntregaEnArray = 1;
		}

		$cantidadDeElementos = $cantidadDeElementos + 1;
	}
/*
	if ($existeEntregaEnArray == 1 and $cantidadDeElementos > 1 ) {
		$message = "Si seleccionó NINGUNA DISCAPACIDAD, solamente esa debe estar, no seleccione otras más!!" ;
		return false;
	}

	if ($existeEntregaEnArray == 1 and $cantidadDeElementos == 1 ) {
		$values['porcentaje_discapacidad'] = 0;
	}
*/

	$values["resumen"] = strtoupper($values["resumen"]);
	$values["domicilio"] = strtoupper($values["domicilio"]);

	return true;
;		
} // function BeforeEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom record update
function CustomEdit(&$values, $where, &$oldvalues, &$keys, &$error, $inline, $pageObject)
{

			//Borrar y volver a cargar discapacidades
	$sqldisb = DB::PrepareSQL("DELETE FROM eportal.persons_discapacidades WHERE person_id = ':1'", $keys["id"]);
	DB::Exec($sqldisb);
	//Insertar discapacidad
	$zonas_cuerpo = explode(",", $values["multiselect_discapacidades"]);
	foreach ($zonas_cuerpo as $value) {
		$sqldis = DB::PrepareSQL("INSERT INTO eportal.persons_discapacidades(person_id, tipo_discapacidad_id) 
																	VALUES (':1',':2')", $keys["id"], $value);
		DB::Exec($sqldis);
	}
	
	
	//Borrar y volver a cargar numero de telefono
	$sqldisb = DB::PrepareSQL("DELETE FROM eportal.persons_phones WHERE person_id = ':1'", $keys["id"]);
	DB::Exec($sqldisb);
	//Insertar numero de telefono
	$sqltel = DB::PrepareSQL("INSERT INTO eportal.persons_phones(person_id, type, phone) 
															VALUES (':1', 2, ':2')", $keys["id"], $values["nro_cel"]);
	DB::Exec($sqltel);
	

	if (empty($oldvalues["foto"])) {
	  $sql = "UPDATE eportal.persons 
							SET
									domicilio = '".pg_escape_string($values["domicilio"])."',
									estado_civil = '".pg_escape_string($values["estado_civil"])."', 
									city_id = '".pg_escape_string($values["city_id"])."', 
									distrito_id = '".pg_escape_string($values["distrito_id"])."',
									/*foto = '".pg_escape_bytea($values["foto"])."',*/ 					
									resumen = '".pg_escape_string($values["resumen"])."' 
							WHERE id = '".pg_escape_string($keys["id"])."'";
		CustomQuery($sql);
  }

	if (!empty($values["foto"])) {
		$sql2 = "UPDATE eportal.persons 
							SET 
									domicilio = '".pg_escape_string($values["domicilio"])."',
									estado_civil = '".pg_escape_string($values["estado_civil"])."', 
									city_id = '".pg_escape_string($values["city_id"])."', 
									distrito_id = '".pg_escape_string($values["distrito_id"])."',								
									foto = '".pg_escape_bytea($values["foto"])."', 							
									resumen = '".pg_escape_string($values["resumen"])."'  
								WHERE id = '".pg_escape_string($keys["id"])."'";
		  CustomQuery($sql2);
 }
	
	if (!empty($oldvalues["foto"])) {
		$sql3 = DB::PrepareSQL("UPDATE eportal.persons 
                            SET 
                                domicilio = ':1', 
                                estado_civil = ':2', 
                                city_id = ':3', 
                                distrito_id = ':4',
                                resumen = ':5' 
                            WHERE id = ':6'",														
																		$values["domicilio"],
																		$values["estado_civil"],
																		$values["city_id"],
																		$values["distrito_id"],																
																		$values["resumen"],
																		$keys["id"]);
        DB::Exec($sql3);
    }
		
    return false;
;		
} // function CustomEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Process record values
function ProcessValuesEdit(&$values, $pageObject)
{

				//**********  Check if specific record exists  ************//
  /*
  $strSQLExists = DB::PrepareSQL("SELECT string_agg(CAST(tipo_discapacidad_id AS varchar), ',') 
                                    FROM eportal.persons_discapacidades 
                                    WHERE person_id = ':1'", $values["id"]);
    $rsExists = DB::Query($strSQLExists);
    $data = $rsExists->fetchAssoc();
    if ($data) {
        $values['multiselect_discapacidades'] = $data["string_agg"];
    }
*/

    $strSQLExists2 = DB::PrepareSQL("SELECT phone 
                                     FROM eportal.persons_phones 
                                     WHERE type = 2 
                                     AND person_id = ':1' 
                                     LIMIT 1", $values["id"]);
    $rsExists2 = DB::Query($strSQLExists2);
    $data2 = $rsExists2->fetchAssoc();
    if ($data2) {
        $values['nro_cel'] = $data2["phone"];
    }


		//Oculta el boton "Guardar Cambios"	
		//$pageObject->hideItem("custom_button", $recordId);
		//Oculta el boton "Guardar"(El que esta por default)
		$pageObject->hideItem("edit_save", $recordId);
;		
} // function ProcessValuesEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

				verificardatospostulacion();

;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowEdit(&$xt, &$templatefile, $values, $pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.

$pageObject->hideItem("integrated_edit_field18", $recordId); //Ocultar el id de postulacion
;		
} // function BeforeShowEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
