<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_personas_pasos  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeEdit"]=true;

		$this->events["CustomEdit"]=true;

		$this->events["ProcessValuesEdit"]=true;



		$this->events["AfterEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record updated
function BeforeEdit(&$values, &$sqlValues, $where, &$oldvalues, &$keys, &$message, $inline, $pageObject)
{

				$cantidadDeElementos = 0;
    $existeEntregaEnArray = 0;
    
    //verificar que sea valido seleccion de discapacidades
    $id_multados_multi = explode(",", $values['multiselect_discapacidades']);
    
    foreach ($id_multados_multi as $valueToInsert) {
			if ($valueToInsert == '1') {
				$existeEntregaEnArray = 1;
			}
		
     $cantidadDeElementos = $cantidadDeElementos + 1;
		}
    
    if ($existeEntregaEnArray == 1 and $cantidadDeElementos > 1 ) {
				$message = "Si seleccionó NINGUNA DISCAPACIDAD, solamente esa debe estar, no seleccione otras más!!" ;
        return false;
    }
    
    if ($existeEntregaEnArray == 1 and $cantidadDeElementos == 1 ) {
			$values['porcentaje_discapacidad'] = 0;
    }

    $values["resumen"] = strtoupper($values["resumen"]);
    $values["domicilio"] = strtoupper($values["domicilio"]);

    return true;
;		
} // function BeforeEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom record update
function CustomEdit(&$values, $where, &$oldvalues, &$keys, &$error, $inline, $pageObject)
{

		    //borrar y volver a cargar discapacidades
    $sqldisb = DB::PrepareSQL("DELETE FROM eportal.persons_discapacidades WHERE person_id = ':1'", $keys["id"]);
    DB::Exec($sqldisb);

    //insertar discapacidad
    $zonas_cuerpo = explode(",", $values["multiselect_discapacidades"]);
    foreach ($zonas_cuerpo as $value) {
        $sqldis = DB::PrepareSQL("INSERT INTO eportal.persons_discapacidades(person_id, tipo_discapacidad_id) VALUES (':1',':2')", $keys["id"], $value);
        DB::Exec($sqldis);
    }

    //borrar y volver a cargar tel
    $sqldisb = DB::PrepareSQL("DELETE FROM eportal.persons_phones WHERE person_id = ':1'", $keys["id"]);
    DB::Exec($sqldisb);

    //insertar tel
    $sqltel = DB::PrepareSQL("INSERT INTO eportal.persons_phones(person_id, type, phone) VALUES (':1', 2, ':2')", $keys["id"], $values["nro_cel"]);
    DB::Exec($sqltel);
    
    if (empty($oldvalues["foto"])) {
        $sql2 = "UPDATE eportal.persons 
                    SET canthijos = '".pg_escape_string($values["canthijos"])."',
                        domicilio = '".pg_escape_string($values["domicilio"])."',
                        estado_civil = '".pg_escape_string($values["estado_civil"])."', 
                        city_id = '".pg_escape_string($values["city_id"])."', 
                        distrito_id = '".pg_escape_string($values["distrito_id"])."',
                        esindigena = '".pg_escape_string($values["esindigena"])."', 
                        foto = '".pg_escape_bytea($values["foto"])."', 
                        porcentaje_discapacidad = '".pg_escape_string($values["porcentaje_discapacidad"])."',
                        adjunto_certificado_discapacidad = '".pg_escape_string($values["adjunto_certificado_discapacidad"])."', 
                        adjunto_potencial_discapacidad = '".pg_escape_string($values["adjunto_potencial_discapacidad"])."', 
                        resumen = '".pg_escape_string($values["resumen"])."' 
                    WHERE id = '".pg_escape_string($keys["id"])."'";
        CustomQuery($sql2);
    }


    if (!empty($values["foto"])) {
        $sql2 = "UPDATE eportal.persons 
                    SET canthijos = '".pg_escape_string($values["canthijos"])."',
                        domicilio = '".pg_escape_string($values["domicilio"])."',
                        estado_civil = '".pg_escape_string($values["estado_civil"])."', 
                        city_id = '".pg_escape_string($values["city_id"])."', 
                        distrito_id = '".pg_escape_string($values["distrito_id"])."',
                        esindigena = '".pg_escape_string($values["esindigena"])."', 
                        foto = '".pg_escape_bytea($values["foto"])."', 
                        porcentaje_discapacidad = '".pg_escape_string($values["porcentaje_discapacidad"])."',
                        adjunto_certificado_discapacidad = '".pg_escape_string($values["adjunto_certificado_discapacidad"])."', 
                        adjunto_potencial_discapacidad = '".pg_escape_string($values["adjunto_potencial_discapacidad"])."', 
                        resumen = '".pg_escape_string($values["resumen"])."'  
                    WHERE id = '".pg_escape_string($keys["id"])."'";
        CustomQuery($sql2);
    }


    if (!empty($oldvalues["foto"])) {
        $sql2 = DB::PrepareSQL("UPDATE eportal.persons 
                                    SET canthijos = ':1',
                                        domicilio = ':2', 
                                        estado_civil = ':3', 
                                        city_id = ':4', 
                                        distrito_id = ':5',
                                        esindigena = ':6', 
                                        porcentaje_discapacidad = ':7',
                                        adjunto_certificado_discapacidad = ':8', 
                                        adjunto_potencial_discapacidad = ':9', 
                                        resumen = ':10'  
                                    WHERE id = ':11'",
                                    $values["canthijos"],
                                    $values["domicilio"],
                                    $values["estado_civil"],
                                    $values["city_id"],
                                    $values["distrito_id"],
                                    $values["esindigena"],
                                    $values["porcentaje_discapacidad"], 
                                    $values["adjunto_certificado_discapacidad"],
                                    $values["adjunto_potencial_discapacidad"],
                                    $values["resumen"],
                                    $keys["id"]);
        DB::Exec($sql2);
    }

    return false;
;		
} // function CustomEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Process record values
function ProcessValuesEdit(&$values, $pageObject)
{

				//**********  Check if specific record exists  ************//
    $strSQLExists = DB::PrepareSQL("SELECT string_agg(CAST(tipo_discapacidad_id AS varchar), ',') 
                                    FROM eportal.persons_discapacidades 
                                    WHERE person_id = ':1'", $values["id"]);
    $rsExists = DB::Query($strSQLExists);
    $data = $rsExists->fetchAssoc();
    if ($data) {
        $values['multiselect_discapacidades'] = $data["string_agg"];
    }

    $strSQLExists2 = DB::PrepareSQL("SELECT phone 
                                        FROM eportal.persons_phones 
                                        WHERE type = 2 
                                        AND person_id = ':1' 
                                        LIMIT 1", $values["id"]);
    $rsExists2 = DB::Query($strSQLExists2);
    $data2 = $rsExists2->fetchAssoc();
    if ($data2) {
        $values['nro_cel'] = $data2["phone"];
    }
;		
} // function ProcessValuesEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		
		$pageObject->setMessageType(MESSAGE_INFO);
    $pageObject->setMessage("Registro Actualizado Correctamente");

    verificardatospostulacion();



;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
