<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_vacancia  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeShowList"]=true;


		$this->events["BeforeMoveNextList"]=true;

		$this->events["BeforeProcessList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

		$pageObject->hideItem("simple_grid_field2");
$pageObject->hideItem("simple_grid_field4");
//$pageObject->hideItem("grid_field4");






//**********  Check if specific record exists  ************

$rs = DB::Query("select 
							count(v.id_vacancias) conteo,
							sum ( v.cantidad_vacancia  ) as sumatoria
							from bolsa_empleo.vacancia v 
							where v.id_estado_vacancia::integer =2;");
$data=$rs->fetchAssoc();
if($data)
{
   $xt->assign('var_total', '<span style ="text-shadow: rgb(0, 0, 0) 0px 1px 1px, rgb(0, 0, 0) 0px -1px 1px, rgb(0, 0, 0) 1px 0px 1px, rgb(0, 0, 0) -1px 0px 1px !important:" ><strong>'.$data['sumatoria'].'</strong> </span>');
}
 
;		
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		//estado activo
//habilitar compartir y postularse
if ($data['id_estado']==2){
$pageObject->hideItem("custom_cancelar_postu",$recordId);
$strSQLExistsl = "SELECT
	*
FROM
	bolsa_empleo.postulacion
WHERE
id_vacancia='".pg_escape_string($data["id_vacancias"])."' and fk_personaid='".pg_escape_string($_SESSION["persona_id"])."' ";

$rsExistsl = db_query($strSQLExistsl,$conn);

$datal=db_fetch_array($rsExistsl);

	if($datal){
  //ya se postulo!
			$pageObject->hideItem("custom_postularse",$recordId);//postularse
			$pageObject->showItem("custom_cancelar_postu",$recordId);//cancelar postulacion
			$pageObject->hideItem("custom_button",$recordId);//cancelar postulacion

		}

} //fin estado activo
//vacancia cerrada
if ($data['id_estado']==5){
	$pageObject->hideItem("custom_postularse",$recordId);//postularse
			$pageObject->hideItem("custom_cancelar_postu",$recordId);//cancelar postulacion
			$pageObject->hideItem("custom_button",$recordId);//cancelar postulacion
$pageObject->hideItem("grid_field4", $recordId); 
}





;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

				// List page: Before process
function BeforeProcessList($pageObject)
{

		$pageObject->hideItem("verificar_datos_bt");

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
