<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_vista_estudios_realizados_union_mec  extends eventsBase
{
	function __construct()
	{
	// fill list of events

		$this->events["BeforeShowAdd"]=true;

		$this->events["BeforeShowEdit"]=true;



		$this->events["BeforeShowList"]=true;

		$this->events["BeforeMoveNextList"]=true;

		$this->events["BeforeEdit"]=true;

		$this->events["BeforeAdd"]=true;

		$this->events["CustomAdd"]=true;

		$this->events["CustomEdit"]=true;

		$this->events["AfterAdd"]=true;



	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowAdd(&$xt, &$templatefile, $pageObject)
{

			$pageObject->hideItem("integrated_edit_field1");//oculta el campo persona_id

	//$pageObject->hideItem("integrated_edit_field7");//oculta el campo anhos
;		
} // function BeforeShowAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowEdit(&$xt, &$templatefile, $values, $pageObject)
{

			$pageObject->hideItem("integrated_edit_field");
	//$pageObject->hideItem("integrated_edit_field1");
;		
} // function BeforeShowEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

			$pageObject->hideItem("simple_grid_field1"); //oculta el campo persona_id

	$xt->assign("message", "Sin Datos. Añadir Información");
;		
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

			if ($data["proveedor"] == "MEC" || $data["proveedor"] == "SNPP"){
		$pageObject->hideItem("grid_edit", $recordId);
		$pageObject->hideItem("custom_button", $recordId);
	}

;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record updated
function BeforeEdit(&$values, &$sqlValues, $where, &$oldvalues, &$keys, &$message, $inline, $pageObject)
{

			$values["titulo_obtenido"] = strtoupper($values["titulo_obtenido"]);

	return true;
;		
} // function BeforeEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$sqlValues, &$message, $inline, $pageObject)
{

			$values["titulo_obtenido"] = strtoupper($values["titulo_obtenido"]);

	return true;
;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom add
function CustomAdd(&$values, &$keys, &$error, $inline, $pageObject)
{

			function debug_to_console($data, $context = 'Debug in Console') {
		// Buffering to solve problems frameworks, like header() in this and not a solid return.
		ob_start();
		
		$output  = 'console.info(\'' . $context . ':\');';
		$output .= 'console.log(' . json_encode($data) . ');';
		$output  = sprintf('<script>%s</script>', $output);
		
		echo $output;
	}

	$sql1 = DB::PrepareSQL("INSERT INTO bolsa_empleo.cvc_estudios_realizados(fk_personaid, 
																		fecha_hasta, 
																		fecha_desde, 
																		fk_cvc_instituciones_educativas, 
																		fk_cvc_niveles_academicos, 
																		titulo_obtenido, 
																		anhos) 
														VALUES (':1',':2',':3',':4',':5',':6',':7');", 
														$_SESSION["persona_id"], 
														$values["fecha_hasta"], 
														$values["fecha_desde"], 
														$values["fk_cvc_instituciones_educativas"], 
														$values["fk_cvc_niveles_academicos"], 
														$values["titulo_obtenido"], 
														$values["anhos"]
													);
	
	debug_to_console($sql1);
	
	DB::Exec($sql1);

	return false;
;		
} // function CustomAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom record update
function CustomEdit(&$values, $where, &$oldvalues, &$keys, &$error, $inline, $pageObject)
{

			function debug_to_console($data, $context = 'Debug in Console') {
		// Buffering to solve problems frameworks, like header() in this and not a solid return.
		ob_start();
		
		$output  = 'console.info(\'' . $context . ':\');';
		$output .= 'console.log(' . json_encode($data) . ');';
		$output  = sprintf('<script>%s</script>', $output);
		
		echo $output;
	}
	
	$sql2 = DB::PrepareSQL("
		update bolsa_empleo.cvc_estudios_realizados 
		set fecha_hasta = ':1',
				fecha_desde = ':2', 
				fk_cvc_instituciones_educativas = ':3', 
				fk_cvc_niveles_academicos = ':4', 
				titulo_obtenido = ':5',
				anhos = ':6' 
		where id_estudios_realizados = ':7'", 
		$values["fecha_hasta"], 
		$values["fecha_desde"], 
		$values["fk_cvc_instituciones_educativas"], 
		$values["fk_cvc_niveles_academicos"],
		$values["titulo_obtenido"],
		$values["anhos"],
		$values["id"]
		);
		
		DB::Exec($sql2);
		
		debug_to_console($sql2);

		return false;
;		
} // function CustomEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

			$textoresultados = array();
	$falta_datos = 0;

	$rs = DB::Query("SELECT
											(SELECT foto FROM eportal.persons WHERE id = '".pg_escape_string($_SESSION["persona_id"])."') AS existe_foto,
											(SELECT resumen FROM eportal.persons WHERE id = '".pg_escape_string($_SESSION["persona_id"])."') AS existe_resumen,
											(SELECT COUNT(*) FROM eportal.persons_phones WHERE person_id = '".pg_escape_string($_SESSION["persona_id"])."') AS count_phones,
											(SELECT city_id FROM eportal.persons WHERE id = '".pg_escape_string($_SESSION["persona_id"])."') AS existe_city,
											(SELECT domicilio FROM eportal.persons WHERE id = '".pg_escape_string($_SESSION["persona_id"])."') AS existe_domicilio,
											(SELECT canthijos FROM eportal.persons WHERE id = '".pg_escape_string($_SESSION["persona_id"])."') AS existe_canthijos,
											(SELECT COUNT(*) FROM bolsa_empleo.vista_estudios_realizados_union_mec WHERE nro_documento = '".pg_escape_string($_SESSION["cedula"])."') AS count_educacion
										");
	while ($datafinal = $rs->fetchAssoc()) {
		$existe_foto = $datafinal['existe_foto'];
		$existe_resumen = $datafinal['existe_resumen'];
		$count_phones = $datafinal['count_phones'];
		$existe_city = $datafinal['existe_city'];
		$existe_domicilio = $datafinal['existe_domicilio'];
		$existe_canthijos = $datafinal['existe_canthijos'];
		$count_educacion = $datafinal['count_educacion'];

		if (is_null($existe_foto)) {
			// $textoresultados[] = '<br><i class="bi bi-dot"></i> '."Foto de Perfil en Informacion Personal.";
			// $falta_datos = 1;
		}

		if (is_null($existe_resumen)) {
			$textoresultados[] = '<br><i class="bi bi-dot"></i> '."Resumen Personal <a href='personas_pasos_edit.php'>Ir a información personal</a>";
			$falta_datos = 1;
		}

		if ($count_phones < 1) {
			$textoresultados[] = '<br><i class="bi bi-dot"></i> '."1 Numero de Contacto <a href='personas_pasos_edit.php'>Ir a teléfonos</a>";
			$falta_datos = 1;
		}

		if (is_null($existe_city)) {
			$textoresultados[] = '<br><i class="bi bi-dot"></i> '."Ciudad <a href='personas_pasos_edit.php'>Ir a información personal</a>";
			$falta_datos = 1;
		}

		if (is_null($existe_domicilio)) {
			$textoresultados[] = '<br><i class="bi bi-dot"></i> '."Dirección. <a href='personas_pasos_edit.php'>Ir a información personal</a>";
			$falta_datos = 1;
		}

		if (is_null($existe_canthijos)) {
			$textoresultados[] = '<br><i class="bi bi-dot"></i> '."Cantidad Hijos <a href='personas_pasos_edit.php'>Ir a información personal</a>";
			$falta_datos = 1;
		}

		if ($count_educacion < 1 ) {
			$textoresultados[] = '<br><i class="bi bi-dot"></i> '."1 Entidad Educativa <a href='vista_estudios_realizados_union_mec_list.php'>Ir a Estudios Realizados</a>";
			$falta_datos = 1;
		}
	}

	if ($falta_datos == '0' ) {
		$pageObject->setMessageType(MESSAGE_INFO);
		$Mensaje = '<h4><span style="color: #000000; ">Información Registrada Correctamente</span></h4><p style="color: #000000; "> ¡Ahora puedes postularte!</p>
								<div>
									<a class="btn btn-sm btn-success" href="vacancia_list.php" id="viewPageButton1">Ir a las Ofertas Laborales</a>
								</div>';
		$pageObject->setMessage($Mensaje);
	}

;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
