<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_vista_curriculum  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeEdit"]=true;

		$this->events["CustomEdit"]=true;

		$this->events["ProcessValuesEdit"]=true;




	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record updated
function BeforeEdit(&$values, &$sqlValues, $where, &$oldvalues, &$keys, &$message, $inline, $pageObject)
{

		$cantidaddeelementos = 0;

$existeentregaenarray = 0;


//verificar que sea valido seleccion de discapacidades



$id_multados_multi = explode(",",$values['multiselect_discapacidades']);


      foreach ($id_multados_multi as  $valuetoinsert)
      {
			

				if($valuetoinsert == '1')
				{
					$existeentregaenarray = 1;
				}
				$cantidaddeelementos = $cantidaddeelementos + 1;
						
      }


				if($existeentregaenarray == 1 and $cantidaddeelementos > 1 )
				{
				$message="Si seleccionó NINGUNA DISCAPACIDAD, solamente esa debe estar, no seleccione otras mas!!" ;

				return false;

				}


					if($existeentregaenarray == 1 and $cantidaddeelementos == 1 )
				{
			
				$values['porcentaje_discapacidad'] = 0;

				}

return true;
;		
} // function BeforeEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom record update
function CustomEdit(&$values, $where, &$oldvalues, &$keys, &$error, $inline, $pageObject)
{

		
//borrar y volver a cargar discapacidades

													$sqldisb = DB::PrepareSQL("DELETE FROM eportal.persons_discapacidades where person_id = ':1'",$keys["id"]);
													DB::Exec($sqldisb);

							//insertar discapacidad
											$zonas_cuerpo = explode(",",$values["multiselect_discapacidades"]);
											foreach ($zonas_cuerpo as  $value)
											{
													$sqldis = DB::PrepareSQL("INSERT INTO eportal.persons_discapacidades(person_id,tipo_discapacidad_id) values 
										(':1',':2')",$keys["id"],$value);
													DB::Exec($sqldis);

											}
if (empty($oldvalues["foto"])){

$sql2 = "update eportal.persons set canthijos = '".pg_escape_string($values["canthijos"])."',domicilio = '".pg_escape_string($values["domicilio"])."',
estado_civil = '".pg_escape_string($values["estado_civil"])."', city_id = '".pg_escape_string($values["city_id"])."', distrito_id = '".pg_escape_string($values["distrito_id"])."',
esindigena = '".pg_escape_string($values["esindigena"])."', foto = '".pg_escape_bytea($values["foto"])."', 
porcentaje_discapacidad = '".pg_escape_string($values["porcentaje_discapacidad"])."',
adjunto_certificado_discapacidad = '".pg_escape_string($values["adjunto_certificado_discapacidad"])."', 
 adjunto_potencial_discapacidad = '".pg_escape_string($values["adjunto_potencial_discapacidad"])."', resumen = '".pg_escape_string($values["resumen"])."' 
 where id = '".pg_escape_string($keys["id"])."'";
CustomQuery($sql2);

//$sql2 = DB::PrepareSQL("update eportal.persons set canthijos = ':1',
//domicilio = ':2', estado_civil = ':3', city_id = ':4', distrito_id = ':5',
//esindigena = ':6', foto = ':7', porcentaje_discapacidad = ':8',
//adjunto_certificado_discapacidad = ':9', adjunto_potencial_discapacidad = ':10' 
 //where id = ':11'",$values["canthijos"],$values["domicilio"],$values["estado_civil"],
 //$values["city_id"],$values["distrito_id"],$values["esindigena"],$values["foto"],$values["porcentaje_discapacidad"], 
 //$values["adjunto_certificado_discapacidad"],$values["adjunto_potencial_discapacidad"],$keys["id"]);
//DB::Exec($sql2);
//print_r(DB::LastError());

}


if (!empty($values["foto"])){

$sql2 = "update eportal.persons set canthijos = '".pg_escape_string($values["canthijos"])."',domicilio = '".pg_escape_string($values["domicilio"])."',
estado_civil = '".pg_escape_string($values["estado_civil"])."', city_id = '".pg_escape_string($values["city_id"])."', distrito_id = '".pg_escape_string($values["distrito_id"])."',
esindigena = '".pg_escape_string($values["esindigena"])."', foto = '".pg_escape_bytea($values["foto"])."', 
porcentaje_discapacidad = '".pg_escape_string($values["porcentaje_discapacidad"])."',
adjunto_certificado_discapacidad = '".pg_escape_string($values["adjunto_certificado_discapacidad"])."', 
adjunto_potencial_discapacidad = '".pg_escape_string($values["adjunto_potencial_discapacidad"])."', resumen = '".pg_escape_string($values["resumen"])."'  
 where id = '".pg_escape_string($keys["id"])."'";
CustomQuery($sql2);

//$sql2 = DB::PrepareSQL("update eportal.persons set canthijos = ':1',
//domicilio = ':2', estado_civil = ':3', city_id = ':4', distrito_id = ':5',
//esindigena = ':6', foto = ':7', porcentaje_discapacidad = ':8',
//adjunto_certificado_discapacidad = ':9', adjunto_potencial_discapacidad = ':10' 
 //where id = ':11'",$values["canthijos"],$values["domicilio"],$values["estado_civil"],
 //$values["city_id"],$values["distrito_id"],$values["esindigena"],$values["foto"],$values["porcentaje_discapacidad"], 
 //$values["adjunto_certificado_discapacidad"],$values["adjunto_potencial_discapacidad"],$keys["id"]);
//DB::Exec($sql2);
//print_r(DB::LastError());

}


if (!empty($oldvalues["foto"])){

//$sql2 = "update eportal.persons set canthijos = '".pg_escape_string($values["canthijos"])."',domicilio = '".pg_escape_string($values["domicilio"])."',
//estado_civil = '".pg_escape_string($values["estado_civil"])."', city_id = '".pg_escape_string($values["city_id"])."', distrito_id = '".pg_escape_string($values["distrito_id"])."',
//esindigena = '".pg_escape_string($values["esindigena"])."', 
//porcentaje_discapacidad = '".pg_escape_string($values["porcentaje_discapacidad"])."',
//adjunto_certificado_discapacidad = '".pg_escape_string($values["adjunto_certificado_discapacidad"])."', adjunto_potencial_discapacidad = '".pg_escape_string($values["adjunto_potencial_discapacidad"])."' where id = '".pg_escape_string($keys["id"])."'";
//CustomQuery($sql2);

$sql2 = DB::PrepareSQL("update eportal.persons set canthijos = ':1',
domicilio = ':2', estado_civil = ':3', city_id = ':4', distrito_id = ':5',
esindigena = ':6', porcentaje_discapacidad = ':7',
adjunto_certificado_discapacidad = ':8', adjunto_potencial_discapacidad = ':9', resumen = ':10'  
 where id = ':11'",$values["canthijos"],$values["domicilio"],$values["estado_civil"],
 $values["city_id"],$values["distrito_id"],$values["esindigena"],$values["porcentaje_discapacidad"], 
 $values["adjunto_certificado_discapacidad"],$values["adjunto_potencial_discapacidad"],$values["resumen"],$keys["id"]);
DB::Exec($sql2);
//print_r(DB::LastError());

}

return false;
;		
} // function CustomEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Process record values
function ProcessValuesEdit(&$values, $pageObject)
{

		//**********  Check if specific record exists  ************
//global $conn;
$strSQLExists = DB::PrepareSQL("select string_agg(CAST(tipo_discapacidad_id AS varchar), ',') 
from eportal.persons_discapacidades where person_id = ':1'",$values["id"]);
$rsExists = DB::Query($strSQLExists);
$data=$rsExists->fetchAssoc();
if($data)
{


$values['multiselect_discapacidades']= $data["string_agg"];

}

;		
} // function ProcessValuesEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
